<a href="https://colab.research.google.com/github/dilip-ksa/dilip_ml_pythondemo/blob/main/Day26_ML_journey_Pandas_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([10,20,30,40]) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]

In [ ]:
###### Pandas ###############

In [2]:
import pandas as pd

In [4]:
pd.read_csv('Titanic-Dataset.csv')
#pd.read_csv('Titanic-Dataset.csv',header=None)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data = pd.read_csv('Titanic-Dataset.csv')
print(type(data))
data.Name

<class 'pandas.core.frame.DataFrame'>

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
student = {'Name': ['Ram', 'Radha', 'Mohan'], 'Age': [20,21,21], 'Marks': [89,90,88]}
df = pd.DataFrame(student)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

    Name  Age  Marks
0    Ram   20     89
1  Radha   21     90
2  Mohan   21     88

In [5]:
ls = [10,20,30,40]
df = pd.DataFrame(ls)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

    0
0  10
1  20
2  30
3  40

In [ ]:
df1 = pd.DataFrame(ls, columns=['Marks'])
print(type(df1))
df1

<class 'pandas.core.frame.DataFrame'>

   Marks
0     10
1     20
2     30
3     40

In [ ]:
#Custom row name
df = pd.DataFrame(student, index=['Row1','Row2','Row3'])
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name  Age  Marks
Row1    Ram   20     89
Row2  Radha   21     90
Row3  Mohan   21     88

In [ ]:
#Filter on column
df = pd.DataFrame(student, index=['Row1','Row2','Row3'], columns=['Name', 'Marks'])
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name  Marks
Row1    Ram     89
Row2  Radha     90
Row3  Mohan     88

In [ ]:
#With unknown column
df = pd.DataFrame(student, index=['Row1','Row2','Row3'], columns=['Name', 'Marks', 'C1'])
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name  Marks   C1
Row1    Ram     89  NaN
Row2  Radha     90  NaN
Row3  Mohan     88  NaN

In [ ]:
#datatype
df = pd.DataFrame(student, index=['Row1','Row2','Row3'], dtype='str')
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name Age Marks
Row1    Ram  20    89
Row2  Radha  21    90
Row3  Mohan  21    88

In [ ]:
print(df.dtypes)
print(df.columns)
print(df.size)
print(df.shape)
print(df.ndim)
print(df.values)

Name     object
Age      object
Marks    object
dtype: object
Index(['Name', 'Age', 'Marks'], dtype='object')
9
(3, 3)
2
[['Ram' '20' '89']
 ['Radha' '21' '90']
 ['Mohan' '21' '88']]

In [ ]:
print(data.dtypes)
print(data.columns)

print(data.columns[0:6])

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age'], dtype='object')

In [ ]:
print(data.Age)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [ ]:
#head default 5 row from top
print(data.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [ ]:
#tail default 5 row from buttom
print(data.tail())

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
#head default 5 row from top
print(data.head(8))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S

In [ ]:
data.min(numeric_only=True)

PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

In [ ]:
data.max(numeric_only=True, axis=1)

0       22.0000
1       71.2833
2       26.0000
3       53.1000
4       35.0000
         ...
886    887.0000
887    888.0000
888    889.0000
889    890.0000
890    891.0000
Length: 891, dtype: float64

In [ ]:
data.min(numeric_only=True, axis=1)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
886    0.0
887    0.0
888    0.0
889    0.0
890    0.0
Length: 891, dtype: float64

In [ ]:
data_list = [80, 90,100, 200, 90, 70]
df = pd.DataFrame(data_list)
print(df)
print('Mean:',df.mean())
print('Median:',df.median())

     0
0   80
1   90
2  100
3  200
4   90
5   70
Mean: 0    105.0
dtype: float64
Median: 0    90.0
dtype: float64

In [ ]:
print('Mode:',df.mode())

Mode:     0
0  90

In [ ]:
print('Mode:',data.mode())

Mode:      PassengerId  Survived  Pclass                                   Name  \
0              1       0.0     3.0                    Abbing, Mr. Anthony
1              2       NaN     NaN            Abbott, Mr. Rossmore Edward
2              3       NaN     NaN       Abbott, Mrs. Stanton (Rosa Hunt)
3              4       NaN     NaN                    Abelson, Mr. Samuel
4              5       NaN     NaN  Abelson, Mrs. Samuel (Hannah Wizosky)
..           ...       ...     ...                                    ...
886          887       NaN     NaN                de Mulder, Mr. Theodore
887          888       NaN     NaN              de Pelsmaeker, Mr. Alfons
888          889       NaN     NaN              del Carlo, Mr. Sebastiano
889          890       NaN     NaN        van Billiard, Mr. Austin Blyler
890          891       NaN     NaN            van Melkebeke, Mr. Philemon

      Sex   Age  SibSp  Parch    Ticket  Fare        Cabin Embarked
0    male  24.0    0.0    0.0      1601  8.05      B96 B98        S
1     NaN   NaN    NaN    NaN    347082   NaN  C23 C25 C27      NaN
2     NaN   NaN    NaN    NaN  CA. 2343   NaN           G6      NaN
3     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
4     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
..    ...   ...    ...    ...       ...   ...          ...      ...
886   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
887   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
888   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
889   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN
890   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN

[891 rows x 12 columns]

In [ ]:
print('Mean:',data.mean(numeric_only=True))

Mean: PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [ ]:
##############  Pandas Day2  ###########################

In [ ]:
dict1 = {'Name': ['Ram', 'Radha', 'Mohan', 'Rahul'],
         'Age': [20,21,21, 23],
         'Marks': [89,90,88, 93],
         'Gender': ['M','F','M', 'M'],
         'City': ['BLR', 'RKL', 'DEL', 'BBS']}
df = pd.DataFrame(dict1)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
    Name  Age  Marks Gender City
0    Ram   20     89      M  BLR
1  Radha   21     90      F  RKL
2  Mohan   21     88      M  DEL
3  Rahul   23     93      M  BBS

In [ ]:
#1. Display top 3 rows of a data set
df.head(3)

    Name  Age  Marks Gender City
0    Ram   20     89      M  BLR
1  Radha   21     90      F  RKL
2  Mohan   21     88      M  DEL

Shape of the dataframe and info

In [ ]:
df.shape

(4, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
 3   Gender  4 non-null      object
 4   City    4 non-null      object
dtypes: int64(2), object(3)
memory usage: 292.0+ bytes

In [ ]:
df.isnull()

    Name    Age  Marks  Gender   City
0  False  False  False   False  False
1  False  False  False   False  False
2  False  False  False   False  False
3  False  False  False   False  False

In [ ]:
df.isnull().sum()

Name      0
Age       0
Marks     0
Gender    0
City      0
dtype: int64

In [ ]:
df.isna()

    Name    Age  Marks  Gender   City
0  False  False  False   False  False
1  False  False  False   False  False
2  False  False  False   False  False
3  False  False  False   False  False

In [ ]:
df.isna().sum()

Name      0
Age       0
Marks     0
Gender    0
City      0
dtype: int64

In [ ]:
# default is column oriented
df.isnull().sum()

Name      0
Age       0
Marks     0
Gender    0
City      0
dtype: int64

In [ ]:
df.isnull().sum(axis=0)

Name      0
Age       0
Marks     0
Gender    0
City      0
dtype: int64

In [ ]:
#row oriented check and calculation(sum)
df.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
dtype: int64

In [ ]:
df

    Name  Age  Marks Gender City
0    Ram   20     89      M  BLR
1  Radha   21     90      F  RKL
2  Mohan   21     88      M  DEL
3  Rahul   23     93      M  BBS

In [ ]:
# only numerical column are considered.
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   21.250000  90.000000
std     1.258306   2.160247
min    20.000000  88.000000
25%    20.750000  88.750000
50%    21.000000  89.500000
75%    21.500000  90.750000
max    23.000000  93.000000

In [ ]:
df.describe(include='all')

       Name        Age      Marks Gender City
count     4   4.000000   4.000000      4    4
unique    4        NaN        NaN      2    4
top     Ram        NaN        NaN      M  BLR
freq      1        NaN        NaN      3    1
mean    NaN  21.250000  90.000000    NaN  NaN
std     NaN   1.258306   2.160247    NaN  NaN
min     NaN  20.000000  88.000000    NaN  NaN
25%     NaN  20.750000  88.750000    NaN  NaN
50%     NaN  21.000000  89.500000    NaN  NaN
75%     NaN  21.500000  90.750000    NaN  NaN
max     NaN  23.000000  93.000000    NaN  NaN

In [ ]:
# Find the unique values from Gender
df.Gender

0    M
1    F
2    M
3    M
Name: Gender, dtype: object

In [ ]:
df.Gender.unique()

array(['M', 'F'], dtype=object)

In [ ]:
list(df.Gender.unique())

['M', 'F']

In [ ]:
df['Gender'].unique()

array(['M', 'F'], dtype=object)

In [ ]:
print(df['Gender'].unique())

['M' 'F']

In [ ]:
print(df['Gender'].value_counts())

Gender
M    3
F    1
Name: count, dtype: int64

In [ ]:
print(type(df['Gender'].value_counts()))

<class 'pandas.core.series.Series'>

In [ ]:
#Count values based on filter
print(df['Gender'].value_counts()['M'])

3

In [ ]:
df[df['Marks'] >= 90]

    Name  Age  Marks Gender City
1  Radha   21     90      F  RKL
3  Rahul   23     93      M  BBS

In [ ]:
(df['Marks'] >= 90) & (df['Gender'] == 'M')

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
df[(df['Marks'] >= 90) & (df['Gender'] == 'M')]

    Name  Age  Marks Gender City
3  Rahul   23     93      M  BBS

In [ ]:
type(df[(df['Marks'] >= 90) & (df['Gender'] == 'M')])

pandas.core.frame.DataFrame

In [ ]:
len(df[(df['Marks'] >= 90) & (df['Gender'] == 'M')])

1

In [ ]:
df['Marks'].mean()

np.float64(90.0)

In [ ]:
#Using user defined function
def marks(x):
    return x/2

In [ ]:
#apply the user defined function
df['Half_marks'] = df['Marks'].apply(marks)
df

    Name  Age  Marks Gender City  Half_marks
0    Ram   20     89      M  BLR        44.5
1  Radha   21     90      F  RKL        45.0
2  Mohan   21     88      M  DEL        44.0
3  Rahul   23     93      M  BBS        46.5

In [ ]:
df['Gender_numarical'] = df['Gender'].map({'M':1, 'F':2})
df

    Name  Age  Marks Gender City  Half_marks  Gender_numarical
0    Ram   20     89      M  BLR        44.5                 1
1  Radha   21     90      F  RKL        45.0                 2
2  Mohan   21     88      M  DEL        44.0                 1
3  Rahul   23     93      M  BBS        46.5                 1

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Gender', 'City', 'Half_marks',
       'Gender_numarical'],
      dtype='object')

In [ ]:
#Displays view without column
df.drop('Half_marks', axis=1)

    Name  Age  Marks Gender City  Gender_numarical
0    Ram   20     89      M  BLR                 1
1  Radha   21     90      F  RKL                 2
2  Mohan   21     88      M  DEL                 1
3  Rahul   23     93      M  BBS                 1

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Gender', 'City', 'Half_marks',
       'Gender_numarical'],
      dtype='object')

In [ ]:
#Drops column in df
df.drop('Half_marks', axis=1, inplace=True)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Gender', 'City', 'Gender_numarical'], dtype='object')

In [ ]:
df.sort_values(by='Marks')

    Name  Age  Marks Gender City  Gender_numarical
2  Mohan   21     88      M  DEL                 1
0    Ram   20     89      M  BLR                 1
1  Radha   21     90      F  RKL                 2
3  Rahul   23     93      M  BBS                 1

In [ ]:
df.sort_values(by='Marks', ascending=False)

    Name  Age  Marks Gender City  Gender_numarical
3  Rahul   23     93      M  BBS                 1
1  Radha   21     90      F  RKL                 2
0    Ram   20     89      M  BLR                 1
2  Mohan   21     88      M  DEL                 1

In [ ]:
# Manipulate the csv files
sdata = pd.read_csv('Salaries.csv')
sdata

/tmp/ipython-input-457923915.py:2: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sdata = pd.read_csv('Salaries.csv')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [ ]:
sdata.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [ ]:
sdata.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [ ]:
sdata.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [ ]:
sdata.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [ ]:
sdata.shape

(148654, 13)

In [ ]:
sdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [ ]:
sdata.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [ ]:
sdata.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [ ]:
ndata = sdata.drop(['Id', 'Notes', 'Status', 'Agency'], axis=1)

In [ ]:
ndata.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [ ]:
ndata.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [ ]:
#Overall statistics of columns
ndata.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

In [ ]:
# Count employees occurance
ndata['EmployeeName'].value_counts().head(10)

EmployeeName
Kevin Lee       13
William Wong    11
Richard Lee     11
Steven Lee      11
John Chan        9
Michael Wong     9
KEVIN LEE        9
Stanley Lee      9
William Lee      8
MICHAEL LEE      8
Name: count, dtype: int64

In [ ]:
#9 count unique job titles
print(ndata['JobTitle'].nunique())

2159

In [ ]:
list1 = list(ndata['JobTitle'].unique())
print(list1)
print(len(list1))

['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY', 'CAPTAIN III (POLICE DEPARTMENT)', 'WIRE ROPE CABLE MAINTENANCE MECHANIC', 'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)', 'ASSISTANT DEPUTY CHIEF II', 'BATTALION CHIEF, (FIRE DEPARTMENT)', 'DEPUTY DIRECTOR OF INVESTMENTS', 'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 'EXECUTIVE CONTRACT EMPLOYEE', 'DEPARTMENT HEAD V', 'COMMANDER III, (POLICE DEPARTMENT)', 'CAPTAIN, EMERGENCYCY MEDICAL SERVICES', 'ASSISTANT MEDICAL EXAMINER', 'CAPTAIN, FIRE SUPPRESSION', 'CHIEF OF POLICE', 'DEPUTY CHIEF III (POLICE DEPARTMENT)', 'INSPECTOR III, (POLICE DEPARTMENT)', 'ELECTRONIC MAINTENANCE TECHNICIAN', 'ADMINISTRATOR, SFGH MEDICAL CENTER', 'LIEUTENANT III (POLICE DEPARTMENT)', 'FIREFIGHTER', 'NURSING SUPERVISOR PSYCHIATRIC', 'MAYOR', 'LIEUTENANT, FIRE DEPARTMENT', 'INCIDENT SUPPORT SPECIALIST', 'ANESTHETIST', 'DISTRICT ATTORNEY', 'ELECTRICAL TRANSIT MECHANIC, ASSISTANT SUPERVISOR', 'PORT DIRECTOR', 'LIEUTENANT, BUREAU OF FIRE PREVENTION AND PUBLIC S', 'SENIOR PHYSICIAN SPECIALIST', 'FIRE FIGHTER PARAMEDIC', 'MANAGER VII', 'TRANSIT SUPERVISOR', 'INSPECTOR, BUREAU OF FIRE PREVENTION AND PUBLIC SA', 'MANAGER VIII', 'DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG', 'NURSING SUPERVISOR', 'POLICE OFFICER III', "SHERIFF'S LIEUTENANT", 'DEPUTY DIRECTOR V', 'SUPERVISING PHYSICIAN SPECIALIST', 'DEPARTMENT HEAD IV', 'FORENSIC TOXICOLOGIST', 'CONFIDENTIAL CHIEF ATTORNEY II (CIVIL & CRIMINAL)', 'SERGEANT III (POLICE DEPARTMENT)', 'DEPUTY SHERIFF', 'NURSE MANAGER', 'ELECTRICAL TRANSIT SYSTEM MECHANIC', 'CITY ATTORNEY', 'MARINE ENGINEER OF FIRE BOATS', 'CHIEF ATTORNEY I (CIVIL & CRIMINAL)', 'CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE', 'ELECTRICAL TRANSIT SHOP SUPERVISOR I', 'POLICE OFFICER I', 'POLICE OFFICER II', 'SERGEANT I (POLICE DEPARTMENT)', 'SPECIAL ASSISTANT XXII', 'DEPUTY DIRECTOR IV', 'WIRE ROPE CABLE MAINTENANCE SUPERVISOR', 'PUBLIC DEFENDER', 'SHERIFF', 'HUMAN RESOURCES DIRECTOR', 'INVESTIGATOR, BUREAU OF FIRE INVESTIGATION', 'ASSISTANT CHIEF ATTORNEY II', 'DEPUTY DIRECTOR III', 'PHARMACIST', 'TRANSIT OPERATIONS SPECIALIST', 'DEPARTMENT HEAD III', 'CHIEF PROBATION OFFICER, JUVENILE COURT', "SHERIFF'S SERGEANT", 'ASSISTANT INSPECTOR (POLICE DEPARTMENT)', 'DIAGNOSTIC IMAGING TECH II', 'DIAGNOSTIC IMAGING TECH III', 'CHIEF ADULT PROBATION OFFICER', 'MANAGER VI', 'FIRE SAFETY INSPECTOR II', 'MAINTENANCE MACHINIST', 'ASSISTANT INSPECTOR III (POLICE DEPARTMENT)', 'DEPUTY DIRECTOR I - MUNICIPAL TRANSPORTATION AGE', 'DIRECTOR, EMPLOYEE RELATIONS DIVISION', 'ASSISTANT CHIEF ATTORNEY I', 'TRAIN CONTROLLER', 'PHYSICIAN ASSISTANT', 'PHYSICIAN SPECIALIST', 'AUTOMOTIVE MECHANIC SUPERVISOR I', 'ATTORNEY (CIVIL/CRIMINAL)', 'SERGEANT II (POLICE DEPARTMENT)', 'ELECTRICIAN', 'NURSE PRACTITIONER', 'MECHANICAL SHOP AND EQUIPMENT SUPERINTENDENT', 'HEAD ATTORNEY, CIVIL AND CRIMINAL', 'PRINCIPAL CIVIL ENGINEER', 'ASSOCIATE ENGINEER', 'PROJECT MANAGER IV', 'PILOT OF FIRE BOATS', 'DEPARTMENT HEAD I', 'SENIOR ENGINEER', 'COURT EXECUTIVE OFFICER', 'ENGINEER', 'ASSISTANT SHERIFF', 'BUILDINGS AND GROUNDS MAINTENANCE SUPERINTENDENT', 'ELECTRONIC MAINTENANCE TECHNICIAN ASSISTANT SUPERV', 'CLINICAL PHARMACIST', 'DEPARTMENT HEAD II', 'CLINICAL NURSE SPECIALIST', 'NURSE MIDWIFE', 'ELECTRICAL TRANSIT MECHANIC SUPERVISOR I', 'MANAGER V', 'ATTORNEY FOR THE PUBLIC ADMINISTRATOR', 'CHIEF DEPUTY SHERIFF', 'SENIOR DEPUTY SHERIFF', 'PROJECT MANAGER III', 'TRACK MAINTENANCE WORKER SUPERVISOR I', 'MAYORAL STAFF XVII', 'MANAGER VII - MUNICIPAL TRANSPORTATION AGENCY', 'HEATING AND VENTILATING INSPECTOR', 'ASST. CHIEF PROBATION OFFICER-JUVENILE PROBATION', 'DIRECTOR, INFORMATION TECHNOLOGY GROUP', 'UTILITY PLUMBER SUPERVISOR II', 'COMMUNICATIONS LINE WORKER SUPERVISOR II', 'ASSISTANT INSPECTOR II (POLICE DEPARTMENT)', 'ASSESSOR', 'MANAGER VIII - MUNICIPAL TRANSPORTATION AGENCY', 'MANAGER IV', 'INSPECTOR, (POLICE DEPARTMENT)', 'IS ENGINEER - PRINCIPAL', 'REGISTERED NURSE', 'SPECIAL NURSE', 'INFORMATION SERVICES MANAGER', 'TRANSMISSION LINE SUPERVISOR I', 'SUPERVISING PHARMACIST', 'SEWAGE TREATMENT PLANT SUPERINTENDENT', 'TREASURER', 'SENIOR POWER GENERATION TECHNICIAN', 'DEPUTY DIRECTOR II', "CHIEF DISTRICT ATTORNEY'S INVESTIGATOR", 'LANDSCAPE ARCHITECTURAL ASSOCIATE II', 'ARCHITECTURAL ASSOCIATE  I', 'LANDSCAPE ARCHITECT', 'ARCHITECT', 'STATIONARY ENGINEER', 'PLUMBING INSPECTOR', 'AUTOMOTIVE MECHANIC', 'CHIEF STATIONARY ENGINEER', 'SENIOR COURT STAFF ATTORNEY', 'HEAD PARK PATROL OFFICER', 'UNDERSHERIFF', 'ASSISTANT ELECTRONIC MAINTENANCE TECHNICIAN', "SHERIFF'S CAPTAIN", 'MANAGER III', 'BOARD SECRETARY - MUNICIPAL TRANSPORTATION AGENC', 'WATER CONSTRUCTION AND MAINTENANCE SUPERINTENDENT', 'LIEUTENANT I, (POLICE DEPARTMENT)', 'LIEUTENANT II (POLICE DEPARTMENT)', 'DIAGNOSTIC IMAGING TECH I', 'MANAGER II - MUNICIPAL TRANSPORTATION AGENCY', 'MANAGER VI - MUNICIPAL TRANSPORTATION AGENCY', 'ATTORNEY, TAX COLLECTOR', 'COURT COMMISSIONER', 'PRINCIPAL ADMINISTRATIVE ANALYST', 'SENIOR RADIO TECHNICIAN', 'ADMINISTRATIVE ENGINEER', 'BUILDING INSPECTOR', 'CHIEF WATER SERVICE INSPECTOR', 'POWER GENERATION SUPERVISOR', 'TRANSIT OPERATOR', 'UTILITY PLUMBER SUPERVISOR I', 'RADIOLOGIC TECHNOLOGIST SUPERVISOR', 'DENTIST', 'BUILDING PLANS ENGINEER', 'INSPECTOR II, (POLICE DEPARTMENT)', 'TELECOMMUNICATIONS TECHNICIAN SUPERVISOR', 'SUPERVISING ELECTRONIC MAINTENANCE TECHNICIAN', 'INSTITUTIONAL POLICE SERGEANT', 'TRANSIT POWER LINE SUPERVISOR I', 'SENIOR COUNSELOR, JUVENILE HALL', 'COURT ADMINISTRATOR', 'PLUMBER SUPERVISOR I', 'COURT COMPUTER SYSTEMS MANAGER', 'SENIOR CONSTRUCTION INSPECTOR', 'CRIMINALIST III', 'TRANSIT POWER LINE WORKER', 'SEWER REPAIR SUPERVISOR', 'SENIOR LIGHT RAIL VEHICLE EQUIPMENT ENGINEER', 'TRANSMISSION AND DISTRIBUTION LINE WORKER', 'MANAGER II', 'ARCHITECTURAL ASSOCIATE II', 'AUTOMOTIVE TRANSIT SHOP SUPERVISOR I', 'MANAGER V - MUNICIPAL TRANSPORTATION AGENCY', 'IS PROJECT DIRECTOR', 'TRANSIT CAR CLEANER', 'CHIEF STATIONARY ENGINEER, WATER TREATMENT PLANT', 'PLUMBER', 'DISABILITY ACCESS COORDINATOR', 'AUTOMOTIVE MECHANIC ASSISTANT SUPERVISOR', 'AUTOMOTIVE MACHINIST ASSISTANT SUPERVISOR', 'LAW LIBRARIAN', 'PROJECT MANAGER II', 'SENIOR STATIONARY ENGINEER', 'TRANSIT POWER LINE WORKER SUPERVISOR II', 'ASST. CHIEF, BUREAU OF CLAIMS INVEST. & ADMIN', 'IS BUSINESS ANALYST - PRINCIPAL', 'POWER GENERATION TECHNICIAN II', 'CABLE SPLICER', 'CONSTRUCTION INSPECTOR', 'IS ENGINEER - SENIOR', 'PLANNER V', 'CRIME LABORATORY MANAGER', 'SHEET METAL WORKER SUPERVISOR II', 'COMMUNICATIONS SYSTEMS TECHNICIAN', 'IS ENGINEER - JOURNEY', 'SUPERINTENDENT OF WATER TREATMENT FACILITIES', 'STATION AGENT, MUNICIPAL RAILWAY', 'STRUCTURAL ENGINEER', 'PUBLIC HEALTH NURSE', 'COURT STAFF ATTORNEY II', 'HEAD AIRPORT ELECTRICIAN', 'ASSISTANT DIRECTOR OF CLINICAL SERVICES II', 'FIRE PROTECTION ENGINEER', 'SPECIAL ASSISTANT XVI', 'ASSISTANT DEPUTY DIRECTOR, PORT', 'FIRE RESCUE PARAMEDIC', 'DIRECTOR, FISCAL SERVICES', "DISTRICT ATTORNEY'S INVESTIGATOR", 'TRANSIT PAINT SHOP SUPERVISOR I', 'ELECTRICIAN SUPERVISOR II', "PRINCIPAL DISTRICT ATTORNEY'S INVESTIGATOR", 'BUILDINGS AND GROUNDS MAINTENANCE SUPERVISOR', 'SENIOR WATER SERVICE INSPECTOR', 'IS BUSINESS ANALYST - SENIOR', 'MAINTENANCE CONTROLLER', 'ELECTRICIAN SUPERVISOR I', 'MANAGER, EMPLOYEE RELATIONS DIV', 'TRAFFIC HEARING OFFICER', 'ASSISTANT ENGINEER', 'LANDSCAPE ARCHITECTURAL ASSOCIATE I', 'CHIEF BUILDING INSPECTOR', 'MAINTENANCE MACHINIST SUPERVISOR I', 'MANAGER IV - MUNICIPAL TRANSPORTATION AGENCY', 'UTILITY PLUMBER', 'SENIOR ELECTRICAL INSPECTOR', 'ELECTRICAL INSPECTOR', 'SENIOR STATIONARY ENGINEER, WATER TREATMENT PLANT', 'COMMUNICATION LINE SUPERVISOR I', 'ELECTRICAL LINE WORKER', 'MAYORAL STAFF XVI', 'AIRPORT MECHANICAL MAINTENANCE SUPERVISOR', 'COURT REPORTER COORDINATOR', 'CHIEF PLUMBING INSPECTOR', 'OPERATING ROOM NURSE', 'WELDER', 'MENTAL HEALTH TREATMENT SPECIALIST', 'TRANSPORTATION SAFETY SPECIALIST', 'SENIOR POLICE COMMUNICATIONS DISPATCHER', 'UTILITY SPECIALIST', 'CEMENT FINISHER SUPERVISOR II', 'ASSISTANT COURT REPORTER COORDINATOR', 'PRINCIPAL REAL PROPERTY OFFICER', 'RESEARCH PSYCHOLOGIST', 'LOCKSMITH SUPERVISOR I', 'SUPERVISING CHEMIST', 'SENIOR PLUMBING INSPECTOR', 'OPERATING ENGINEER, UNIVERSAL', 'LABORATORY SERVICES MANAGER', 'MANAGER I', 'MANAGER, UNIFIED FAMILY COURT SERVICES', 'DIRECTOR, HUMAN RESOURCES', 'SENIOR BUILDING INSPECTOR', 'TRANSIT MANAGER II', 'PLANNER IV', 'EMERGENCY MEDICAL SERVICES AGENCY SPECIALIST', 'PUBLIC SAFETY COMMUNICATIONS DISPATCHER', 'WATER OPERATIONS ANALYST', 'CHIEF ELECTRICAL INSPECTOR', 'TRAFFIC SIGNAL ELECTRICIAN', 'AUTOMOTIVE BODY AND FENDER WORKER', 'APPRENTICE STATIONARY ENGINEER', 'AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I', 'AUTOMOTIVE MACHINIST', 'SUPERVISING PURCHASER', 'CHIEF STATIONARY ENGINEER, SEWAGE PLANT', 'COURT COMPUTER FACILITIES COORDINATOR', 'PLUMBER SUPERVISOR II', 'MANAGER III - MUNICIPAL TRANSPORTATION AGENCY', 'CLAIMS INVESTIGATOR', 'STEAMFITTER', 'PROTECTIVE SERVICES SUPERVISOR', 'CARPENTER SUPERVISOR I', 'MAYORAL STAFF XV', 'COUNSELOR, LOG CABIN RANCH', 'CHIEF HOUSING INSPECTOR', "MEDICAL EXAMINER'S INVESTIGATOR II", 'DIRECTOR, JUVENILE HALL', 'IS PROGRAMMER ANALYST - PRINCIPAL', 'TRAF SIGNAL ELECTRICIAN SUP II', 'IS ADMINISTRATOR III', "ASSISTANT CHIEF DISTRICT ATTORNEY'S INVESTIGATOR", 'STEAMFITTER ASSISTANT SUPERVISOR', 'SENIOR STATIONARY ENGINEER, SEWAGE PLANT', 'COURT REPORTER', 'AIRPORT ELECTRICIAN', 'AIRPORT ELECTRICIAN SUPERVISOR', 'COURT MANAGER', 'HEALTH PROGRAM COORDINATOR III', 'SUPERVISING WASTEWATER CONTROL INSPECTOR', 'TRAF SIGNAL ELECTRICIAN SUP I', 'LINE INSPECTOR', 'PRINCIPAL ADMINISTRATIVE ANAYLST II', 'WATER SERVICE INSPECTOR', 'PUBLIC RELATIONS MANAGER', 'SENIOR ENVIRONMENTAL HEALTH INSPECTOR', 'CONTRACT COMPLIANCE OFFICER II', 'SENIOR INDUSTRIAL HYGIENIST DEPT OF PUBLIC HEALTH', 'SAFETY OFFICER', 'AUTOMOTIVE MACHINIST SUPERVISOR I', 'PLANNER IV-ENVIRONMENTAL REVIEW', 'DIVISION DIRECTOR ADULT PROBATION', 'PROTECTIVE SERVICES WORKER', "MEDICAL EXAMINER'S INVESTIGATOR III", 'AUTOMOTIVE SERVICE WORKER', 'DIRECTOR, PROBATE', 'IS ADMINISTRATOR - SUPERVISOR', 'SENIOR HOUSING INSPECTOR', 'SEWER SERVICE WORKER', 'STREET REPAIR SUPERVISOR II', 'ELECTRIC MOTOR REPAIRER', 'COMMUNICATIONS DIRECTOR', 'COURT COMPUTER APPLICATIONS PROGRAMMER', 'DIAGNOSTIC IMAGING TECH IV', 'PROJECT MANAGER I', 'ASPHALT FINISHER SUPERVISOR I', 'TRANSIT MANAGER I', 'CRIMINALIST II', 'CHIEF MICROBIOLOGIST', 'CHIEF SURVEYOR', 'SENIOR ADMINISTRATIVE ANALYST', 'PSYCHIATRIC TECHNICIAN', 'SUPERVISING BIOLOGIST', 'AIRPORT OPERATIONS SUPERVISOR', 'TRANSIT PLANNER IV', 'MEDIA/SECURITY SYSTEMS SUPERVISOR', "SENIOR DISTRICT ATTORNEY'S INVESTIGATOR", 'PRINCIPAL PERSONNEL ANALYST', 'SENIOR PHYSICAL THERAPIST', 'SENIOR OCCUPATIONAL THERAPIST', 'SHELTER VETERINARIAN', 'CHIEF FIRE ALARM DISPATCHER', 'DEPUTY DIRECTOR I', 'EXECUTIVE ASSISTANT TO THE GENERAL MANAGER, RETIRE', 'AIRPORT ECONOMIC PLANNER', 'SWITCH REPAIRER', 'POWER HOUSE ELECTRICIAN SUPERVISOR I', 'SAFETY ANALYST', 'BIOLOGIST III', 'PARKING ENFORCEMENT ADMINISTRATOR', 'PRINCIPAL ENVIRONMENTAL HEALTH INSPECTOR', 'SENIOR EMPLOYEE RELATIONS REPRESENTATIVE', 'PAINTER SUPERVISOR I', 'SENIOR SYSTEMS ACCOUNTANT', 'COUNSELOR, FAMILY COURT SERVICE', 'GOVERNMENT AND PUBLIC AFFAIRS MANAGER', 'ELECTRONIC INSTRUMENTATION TECHNICIAN,WTR PLTNCN', 'CAR AND AUTO PAINTER', 'PERFORMANCE ANALYST III - PROJECT MANAGER', 'UTILITY PLUMBER APPRENTICE', 'PRINCIPAL MANAGEMENT ANALYST', 'LOCKSMITH', 'SENIOR AIRPORT COMMUNICATIONS DISPATCHER', 'SENIOR PROPERTY MANAGER, PORT', 'HEAVY EQUIPMENT OPERATIONS SUPERVISOR', 'MAINTENANCE PLANNER', 'SENIOR STREET INSPECTOR', 'SENIOR REAL PROPERTY OFFICER', 'ASSISTANT DIRECTOR OF CLINICAL SERVICES I', 'TRUCK DRIVER', 'DIRECTOR, PROBATION SERVICES', 'SENIOR CLAIMS INVESTIGATOR', 'TRACK MAINTENANCE WORKER', 'WATER AND POWER MAINTENANCE SUPERVISOR I', 'ASSOCIATE AFFIRMATIVE ACTION COORDINATOR', 'POLICE COMMUNICATIONS SHIFT SUPERVISOR', 'STREET ENVIRONMENTAL SERVICES OPERATIONS SUPERVI', 'ASSISTANT LAW LIBRARIAN', 'CEMENT FINISHER SUPERVISOR I', 'SENIOR PLAN CHECKER', 'STATIONARY ENGINEER, WATER TREATMENT PLANT', 'MAINTENANCE MANAGER', 'CLERK', 'CRANE MECHANIC SUPERVISOR', 'AIRPORT COMMUNICATIONS OPERATOR', 'MANAGER I - MUNICIPAL TRANSPORTATION AGENCY', 'SUPERVISING CLINICAL PSYCHOLOGIST', 'CHEMIST III', 'ARCHITECTURAL ADMINISTRATOR', 'PRINCIPAL REAL PROPERTY APPRAISER', 'GENERAL LABORER SUPERVISOR I', 'SUPERVISING PARTS STOREKEEPER', 'CITY SHOPS ASSISTANT SUPERINTENDENT', 'INDUSTRIAL HYGIENIST', 'HOUSING INSPECTOR', 'MATERIALS COORDINATOR', 'PRINCIPAL PERSONAL PROPERTY AUDITOR', 'STATIONARY ENGINEER, SEWAGE PLANT', 'LICENSED VOCATIONAL NURSE', 'MARITIME MARKETING REPRESENTATIVE', 'COURT COMPUTER SYSTEMS ENGINEER II', 'COURT COMPUTER APPLICATIONS ANALYST', 'SENIOR HUMAN RESOURCES ANALYST', 'PRINCIPAL ENVIRONMENTAL SPECIALIST', 'SUPERVISING ADULT PROBATION OFFICER', 'SUPERVISING PROBATION OFFICER, JUVENILE COURT', 'SUPERVISING AUDITOR', 'CLAIMS ADJUSTER', 'ELEVATOR AND CRANE TECHNICIAN', 'COURT SUPERVISOR II', 'MEMBER, BOARD OF SUPERVISORS', 'PARTS STOREKEEPER', 'WATER CONSERVATION ADMINISTRATOR', 'TRANSIT CAR CLEANER ASSISTANT SUPERVISOR', 'SHEET METAL SUPERVISOR I', 'MAYORAL STAFF XIII', "SENIOR CLAIMS INVESTIGATOR,CITY ATTORNEY'S OFFICE", 'SENIOR MAINTENANCE CONTROLLER', 'GLAZIER', 'FISCAL SERVICES COORDINATOR', 'SECRETARY TO THE PRESIDING JUDGE', 'HEALTH WORKER IV', 'POWER PLANT SUPERVISOR I', 'OCCUPATIONAL THERAPIST', 'SURVEY ASSOCIATE', 'AUTOMOTIVE SERVICE WORKER ASSISTANT SUPERVISOR', 'SENIOR COMMUNITY DEVELOPMENT SPECIALIST I', 'CHIEF VICTIM/WITNESS INVESTIGATOR', 'MEDIA/SECURITY SYSTEMS SPECIALIST', 'MAYORAL STAFF XIV', 'GENERAL LABORER', 'DEPUTY PROBATION OFFICER', 'CARPENTER', 'PARK PATROL OFFICER', 'EXECUTIVE DIRECTOR, SOUTHEAST COMMUNITY FACILITY', 'PHYSICAL THERAPIST', 'SENIOR POWER HOUSE OPERATOR', 'PARKING CONTROL OFFICER', 'SENIOR PERSONNEL ANALYST', 'INSTITUTIONAL POLICE OFFICER', 'PHARMACY TECHNICIAN', 'AUDIOLOGIST', 'ELIGIBILITY WORKER', 'ASSISTANT SUPERINTENDENT RECREATION', 'SHEET METAL WORKER', 'ASPHALT PLANT SUPERVISOR I', 'SENIOR ACCOUNT CLERK', 'COURT INVESTIGATOR', 'STAGE ELECTRICIAN', 'SECURITY ANALYST', 'PRINCIPAL PAYROLL AND PERSONNEL CLERK', 'SENIOR COMMUNITY DEVELOPMENT SPECIALIST II', 'TRAFFIC SIGN MANAGER', 'ELECTRIC MOTOR REPAIR SUPERVISOR I', 'TRANSIT PLANNER III', 'REGULATORY SPECIALIST', 'PROBATE EXAMINER', 'HOSPITAL ELIGIBILITY WORKER SUPERVISOR', 'COURT ASSISTANT - SENIOR, SUPERIOR COURT', 'MUNICIPAL STADIUM GROUNDSKEEPER', 'BRICKLAYER', 'PLANNER III-ENVIRONMENTAL REVIEW', 'ASSISTANT FORENSIC TOXICOLOGIST I', 'FARE INSPECTIONS SUPERVISOR/INVESTIGATOR', 'EMPLOYMENT AND TRAINING SPECIALIST VI', 'PIPE WELDER', 'PARK SECTION SUPERVISOR', 'ENVIRONMENTAL HEALTH INSPECTOR', 'PRINCIPAL FARE COLLECTIONS RECEIVER', 'AIRPORT SAFETY OFFICER', 'MARRIAGE, FAMILY & CHILD COUNSELOR (MFCC)', 'COORDINATOR OF CITIZEN INVOLVEMENT', 'TREE TOPPER SUPERVISOR I', 'COURT INTERPRETER SUPERVISOR', 'SURGICAL PROCEDURES TECHNICIAN', 'PLANNER III', 'MENTAL HEALTH REHABILITATION WORKER', 'PATIENT ACCOUNTS SUPERVISOR', 'STREET INSPECTION SUPERVISOR', 'COMMUNICATIONS DISPATCHER II', 'POWER HOUSE OPERATOR', 'SENIOR MICROBIOLOGIST', 'IS ENGINEER - ASSISTANT', 'ELECTRICAL LINE HELPER', 'ASSISTANT MATERIALS COORDINATOR', "WORKER'S COMPENSATION SUPERVISOR I", 'ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS', 'CLAIMS INVESTIGATOR CITY ATTORNEYS OFFICE', 'IS TRAINER - SENIOR', 'SPEECH PATHOLOGIST', 'NURSING ASSISTANT', 'COURT TRAINING SPECIALIST', 'ENGINEERING ASSOCIATE II', 'CLINICAL PSYCHOLOGIST', 'IS BUSINESS ANALYST', 'GARDENER', 'AIRPORT PROPERTY SPECIALIST I', 'BOARD/COMMISSION SECRETARY III', 'BENEFITS SUPERVISOR', 'LEGISLATIVE ASSISTANT', 'CEMENT MASON', 'LIBRARIAN III', 'REAL PROPERTY OFFICER', 'ASSISTANT RENTAL MANAGER, PORT', 'ORNAMENTAL IRON WORKER SUPERVISOR I', 'FUSION WELDER', 'SUPERVISING WELFARE FRAUD INVESTIGATOR', 'TRAINING COORDINATOR', 'PAINTER', 'SENIOR PARKING CONTROL OFFICER', 'SENIOR PURCHASER', 'PROGRAM SUPPORT ANALYST', 'FOOD SERVICE MANAGER ADMINISTRATOR', 'CONTRACT COMPLIANCE OFFICER I', 'MEDICAL SOCIAL WORK SUPERVISOR', 'WATERSHED FORESTER MANAGER', 'HEAVY EQUIPMENT OPERATIONS ASSISTANT SUPERVISOR', 'ADMINISTRATIVE ANALYST III', 'MOBILE EQUIPMENT SUPERVISOR', 'GENERAL UTILITY MECHANIC', 'ASSOCIATE AUDITOR', 'COURT SUPERVISOR I', 'APPRENTICE STATIONARY ENGINEER, SEWAGE PLANT', 'TRACK MAINTENANCE SUPERINTENDENT,MUNICIPAL RAILWAY', 'PATTERN MAKER', 'EXECUTIVE ASSISTANT TO THE ADMINISTRATOR, S.F.G.H.', 'IS PROGRAMMER ANALYST - SENIOR', 'ASSISTANT CLERK, BOARD OF SUPERVISORS', 'SENIOR REAL PROPERTY APPRAISER', 'EPIDEMIOLOGIST II', 'ADMINISTRATIVE SERVICES MANAGER', 'PILEDRIVER SUPERVISOR I', 'PERSONNEL PAYROLL REPRESENTATIVE', 'STREET INSPECTOR', 'WASTEWATER CONTROL INSPECTOR', 'SENIOR PERSONAL PROPERTY AUDITOR', 'BIOLOGIST I/II', 'SENIOR PSYCHIATRIC SOCIAL WORKER', 'SENIOR HEALTH PROGRAM PLANNER', 'SENIOR ENVIRONMENT SPECIALIST', "SENIOR INVESTIGATOR, OFFICE OF CITIZEN'S COMPLAINT", 'HEALTH CARE ANALYST', 'SENIOR PAYROLL AND PERSONNEL CLERK', 'SECRETARY I', 'SOFT FLOOR COVERER SUPERVISOR', 'APPRENTICE STATIONARY ENGINEER,WATER TREATMENT PLN', 'SECRETARY, COMMISSION ON THE ENVIRONMENT', 'PSYCHIATRIC SOCIAL WORKER', 'MAINTENANCE MACHINIST ASSISTANT SUPERVISOR', 'SENIOR SOCIAL WORKER', 'COORDINATOR, HUMAN RIGHTS COMMISSION', 'SENIOR HEALTH EDUCATOR', 'CURATOR IV', 'COUNSELOR II', 'MUSEUM SECURITY SUPERVISOR', 'SUPERVISOR, TRAFFIC AND STREET SIGNS', 'SENIOR CLERK', 'PRINCIPAL ACCOUNTANT', 'FEASIBILITY ANALYST, PORT', 'AIRPORT POLICE SERVICES AIDE', "MAYOR'S PROGRAM MANAGER", 'PILEDRIVER ENGINE OPERATOR', "SENIOR PUBLIC DEFENDER'S INVESTIGATOR", 'PILE WORKER', 'MENTAL HEALTH HEARING OFFICER', 'ASSISTANT CHIEF VICTIM/WITNESS INVESTIGATOR', 'CHEMIST I/II', 'PARKING METER REPAIRER SUPERVISOR I', 'CONSERVATORSHIP/CASE MGNT SUPV', 'DEPUTY COURT CLERK III', 'AIRPORT COMMUNICATIONS SUPERVISOR', 'PRINCIPAL CLERK', 'PAINTER SUPERVISOR II', 'AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES', 'FORESTER', 'PUBLIC RELATIONS OFFICER', 'EXECUTIVE SECRETARY III', 'CIVIL ENGINEERING ASSOCIATE I', 'AIRPORT EMERGENCY PLANNING COORDINATOR', 'MOBILE EQUIPMENT ASSISTANT SUPERVISOR', 'IS OPERATOR - SUPERVISOR', 'PERSONNEL ANALYST', 'CARPENTER SUPERVISOR II', 'EMPLOYMENT AND TRAINING SPECIALIST V', 'PARKING HEARING EXAMINER', 'GLAZIER SUPERVISOR I', 'SECRETARY, LIBRARY COMMISSION', 'EXECUTIVE SECRETARY TO THE CONTROLLER', 'ASSISTANT CONSTRUCTION INSPECTOR', 'SUPERVISING COURT ADMINISTRATIVE SECRETARY', 'SENIOR PARTS STOREKEEPER', 'ELIGIBILITY WORKER SUPERVISOR', 'MUSEUM GUARD', 'WELFARE FRAUD INVESTIGATOR', 'PRINCIPAL PARTS STOREKEEPER', 'SENIOR MANAGEMENT ASSISTANT', 'ASSOCIATE PERFORMANCE AUDITOR', 'MAINTENANCE ESTIMATOR AND SCHEDULER', 'PATIENT ACCOUNTS MANAGER', 'MARKET RESEARCH SPECIALISTS, PORT', 'SPECIAL ASSISTANT XV', 'SENIOR MARRIAGE, FAMILY & CHILD COUNSELOR (MFCC)', 'TRAINING OFFICER', 'NUTRITIONIST', 'LIBRARIAN II', 'SENIOR GENERAL UTILITY MECHANIC', 'WATER QUALITY TECHNICIAN I/II', 'X-RAY LABORATORY AIDE', 'EMERGENCY PROTECTIVE ORDERS COMMISSIONER', 'SENIOR MEDICAL SOCIAL WORKER', 'HEALTH EDUCATOR', 'IS ADMINISTRATOR I', 'CHIEF NURSERY SPECIALIST', 'POWERHOUSE ELECTRICIAN SUPERVISOR II', 'PROGRAM SPECIALIST SUPERVISOR', 'PORTER', 'IS ADMINISTRATOR II', 'SENIOR CENTRAL PROCESSING AND DISTRIBUTION TECHNIC', 'PAYROLL SUPERVISOR', 'TRIAL DELAY REDUCTION COORDINATOR', 'BUILDING SERVICES TECHNICIAN', 'SENIOR FISCAL TECHNICIAN', 'IS TECHNICIAN - SUPERVISOR', 'EMPLOYMENT & TRAINING SPECIALIST IV', 'PUBLIC HEALTH TEAM LEADER', 'PRINCIPAL INVESTIGATOR, TAX COLLECTOR', 'MICROBIOLOGIST', 'CENTRAL PROCESSING AND DISTRIBUTION TECHNICIAN', 'SIGN WORKER', 'MEDIA TRAINING SPECIALIST', 'MEDICAL RECORDS TECHNICIAN SUPERVISOR', 'CUSTODIAL ASSISTANT SUPERVISOR', 'SENIOR EMPLOYEE ASSISTANCE COUNSELOR', 'MEDIA PRODUCTION SUPERVISOR', 'COMMERCIAL DIVISION ASSISTANT SUPERVISOR', 'CHILD SUPPORT OFFICER III', 'CRIMINAL JUSTICE SPECIALIST II', 

In [ ]:
ndata['JobTitle'].str.contains('CAPTAIN')

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [ ]:
ndata[ndata['JobTitle'].str.contains('CAPTAIN')]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),None,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),None,106088.18,16452.6,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),None,87082.62,110804.3,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",None,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",None,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
8684,JEANNE SEYLER,"CAPTAIN, FIRE SUPPRESSION",None,0.0,9197.14,NaN,104252.48,104252.48,2011
10485,JANE SMITH,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",None,1538.59,18804.68,NaN,94935.27,94935.27,2011
11198,KATHRYN BROWN,CAPTAIN III (POLICE DEPARTMENT),None,0.0,81244.87,NaN,91929.37,91929.37,2011
31297,MARCO CARNIGLIA,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",None,0.0,1203.77,NaN,11043.49,11043.49,2011
34124,JOHN FORBES-3,"CAPTAIN, FIRE SUPPRESSION",None,982.06,2277.34,NaN,3259.40,3259.40,2011

In [ ]:
# 10 job title with CAPTAIN
ndata[ndata['JobTitle'].str.contains('CAPTAIN')].count(axis=0)

EmployeeName        141
JobTitle            141
BasePay             141
OvertimePay         141
OtherPay            141
Benefits              0
TotalPay            141
TotalPayBenefits    141
Year                141
dtype: int64

In [ ]:
len(ndata[ndata['JobTitle'].str.contains('CAPTAIN')])

141

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [ ]:
# 11 display employee name from fire dept
ndata[ndata['JobTitle'].str.contains('FIRE DEPARTMENT', case=False)].EmployeeName

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: object

In [ ]:
ndata[ndata['JobTitle'].str.contains('FIRE DEPARTMENT', case=False)][['EmployeeName', 'JobTitle']]

                EmployeeName                                          JobTitle
4            PATRICK GARDNER      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
6                  ALSON LEE                BATTALION CHIEF, (FIRE DEPARTMENT)
8             MICHAEL MORRIS                BATTALION CHIEF, (FIRE DEPARTMENT)
9         JOANNE HAYES-WHITE            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
10             ARTHUR KENNEY  ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
...                      ...                                               ...
32623           JAMES BARDEN                BATTALION CHIEF, (FIRE DEPARTMENT)
36162     Joanne Hayes-White                            Chief, Fire Department
72926   Joanne M Hayes-White                            Chief, Fire Department
102303        Robert E Evans                        Captain, (Fire Department)
110535  Joanne M Hayes-White                            Chief, Fire Department

[226 rows x 2 columns]

In [ ]:
#12 find min, max, avg of base pay
ndata['BasePay'].describe()

count     148049.0
unique    109900.0
top            0.0
freq         875.0
Name: BasePay, dtype: float64

In [ ]:
ndata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148049 non-null  object
 3   OvertimePay       148654 non-null  object
 4   OtherPay          148654 non-null  object
 5   Benefits          112495 non-null  object
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
dtypes: float64(2), int64(1), object(6)
memory usage: 10.2+ MB

In [ ]:
ndata['BasePay'] = ndata['BasePay'].replace('Not Provided', np.nan)

In [ ]:
ndata

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,NaN,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [ ]:
ndata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  object
 3   OvertimePay       148654 non-null  object
 4   OtherPay          148654 non-null  object
 5   Benefits          112495 non-null  object
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
dtypes: float64(2), int64(1), object(6)
memory usage: 10.2+ MB

In [ ]:
ndata['BasePay'] = pd.to_numeric(ndata['BasePay'], errors='coerce')
#ndata['BasePay'] = ndata['BasePay'].astype(float)

In [ ]:
ndata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148654 non-null  object
 4   OtherPay          148654 non-null  object
 5   Benefits          112495 non-null  object
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
dtypes: float64(3), int64(1), object(5)
memory usage: 10.2+ MB

In [ ]:
ndata['BasePay'].describe()

count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

In [ ]:
ndata['BasePay'].min()

-166.01

In [ ]:
#15
ndata[ndata.EmployeeName=='ALBERT PARDINI'].JobTitle

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

In [ ]:
#16 How Much ALBERT PARDINI Make (Include Benefits)?
ndata[ndata.EmployeeName=='ALBERT PARDINI']

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [ ]:
albert = ndata[ndata.EmployeeName=='ALBERT PARDINI']
albert['BasePay'] + albert['OvertimePay'] + albert['OtherPay']

2    335279.91
dtype: object

In [ ]:
#17
ndata[ndata['BasePay'].max() == ndata['BasePay']]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
72925,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013

In [ ]:
#18 Find Top 5 Most Common Jobs
ndata['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [17]:
d1 = [1,2,3,4]
df1 = pd.DataFrame(d1)


d2 = [3,4,5,6]
df2 = pd.DataFrame(d2)


#df1[~df1.isin(df2)]
#df1[df1.isin(df2)]
#df2[df2.isin(df1)]
print(df2.isin(df1))

       0
0  False
1  False
2  False
3  False